<a href="https://colab.research.google.com/github/ritik1804k/Hotel-Booking-Analysis/blob/main/EDA%20ON%20FIFA%20%20World%20Cup%202022%20Players%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
# giving some playerd their jersey names
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [4]:
# uploading the csv file to the Qatar FIFA stadium 
path  = '/content/drive/MyDrive/Colab Notebooks/access the data/FIFA dataset/FIFA WC 2022 Players Stats.csv'
FIFA_df = pd.read_csv(path)

In [5]:
# viewing column and the data inside them and how they correlate
FIFA_df.head(10)

,Nationality,FIFA Ranking,National Team Kit Sponsor,Position,National Team Jersey Number,Player DOB,Club,Player Name,Appearances,Goals Scored,Assists Provided,Dribbles per 90,Interceptions per 90,Tackles per 90,Total Duels Won per 90,Save Percentage,Clean Sheets,Brand Sponsor/Brand Used
0,Argentina,2,Adidas,GK,23.0,"Sep 2, 1992",Aston Villa,Emiliano Martinez,7,0,0,0.00,0.00,0.00,0.65,46.67%,43%,Adidas
1,Argentina,2,Adidas,GK,1.0,"Oct 16, 1986",River,Franco Armani,0,-,-,-,-,-,-,-,-,Nike
2,Argentina,2,Adidas,GK,12.0,"May 20, 1992",Villarreal,Geronimo Rulli,0,-,-,-,-,-,-,-,-,Adidas
3,Argentina,2,Adidas,DF,19.0,"Feb 12, 1988",Benfica,Nicolas Otamendi,7,0,1,0.33,1.17,1.30,7.17,-,-,Nike
4,Argentina,2,Adidas,DF,8.0,"Oct 28, 1991",Sevilla,Marcos Acuna,6,0,0,1.45,0.48,2.90,7.97,-,-,Nike
5,Argentina,2,Adidas,DF,3.0,"Aug 31, 1992",Lyon,Nicolas Tagliafico,6,0,0,0.48,2.17,1.69,5.07,-,-,Nike
6,Argentina,2,Adidas,DF,6.0,"Jun 27, 1991",Real Betis,German Pezzella,3,0,0,0.00,0.00,0.00,3.16,-,-,Nike
7,Argentina,2,Adidas,DF,26.0,"Apr 6, 1998",Atletico Madrid,Nahuel Molina,7,1,1,0.32,0.47,1.42,1.58,-,-,Nike
8,Argentina,2,Adidas,DF,4.0,"Jan 1, 1997",Sevilla,Gonzalo Montiel,4,0,0,0.77,0.77,2.31,5.39,-,-,NIke
9,Argentina,2,Adidas,DF,2.0,"Jan 12, 1998",Villarreal,Juan Foyth,1,0,0,N.A,0.00,0.00,N.A,-,-,Adidas

In [6]:
#  bottom ten rows of dataframe
FIFA_df.tail(10)

,Nationality,FIFA Ranking,National Team Kit Sponsor,Position,National Team Jersey Number,Player DOB,Club,Player Name,Appearances,Goals Scored,Assists Provided,Dribbles per 90,Interceptions per 90,Tackles per 90,Total Duels Won per 90,Save Percentage,Clean Sheets,Brand Sponsor/Brand Used
804,Canada,53,Nike,MF,8.0,"Feb 13, 1998",KMSK Deinze,Liam Fraser,N.A,N.A,N.A,N.A,N.A,N.A,N.A,-,-,Adidas
805,Canada,53,Nike,MF,15.0,"Jun 6, 2002",Watford,Ismael Kone,3,0,0,0.00,0.00,0.00,0.86,-,-,Nike
806,Canada,53,Nike,FW,9.0,"Dec 28, 1992",Vancouver Whitecaps,Lucas Cavallini,1,0,0,0.00,0.00,0.00,0.00,-,-,Nike
807,Canada,53,Nike,FW,10.0,"Jun 5, 1990",Reading,Junior Hoilett,3,0,0,1.33,0.56,4.44,8.33,-,-,Nike
808,Canada,53,Nike,FW,11.0,"Feb 8, 1999",Club Brugge,Tajon Buchanan,3,0,1,6.21,1.03,0.34,5.17,-,-,Adidas
809,Canada,53,Nike,FW,17.0,"Apr 17, 1995",Club Brugge,Cyle Larin,3,0,0,1.33,0.00,0.00,1.95,-,-,Nike
810,Canada,53,Nike,FW,19.0,"Nov 2, 2000",Bayern Munich,Alphonso Davies,3,1,0,6.00,1.00,0.67,6.67,-,-,Nike
811,Canada,53,Nike,FW,20.0,"Jan 14, 2000",Lille,Jonathan David,3,0,0,1.41,0.00,0.47,1.88,-,-,Adidas
812,Canada,53,Nike,FW,23.0,"Sep 27, 1999",Basel,Liam Millar,1,0,0,0.00,0.00,0.00,0.00,-,-,Adidas
813,Canada,53,Nike,FW,12.0,"Sep 21, 1998",Troyes,Ike Ugbo,N.A,N.A,N.A,N.A,N.A,N.A,N.A,-,-,Nike

In [7]:
# checking for columns those are empty
FIFA_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 814 entries, 0 to 813
Data columns (total 18 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Nationality                  814 non-null    object
 1   FIFA Ranking                 814 non-null    int64
 2   National Team Kit Sponsor    813 non-null    object
 3   Position                     814 non-null    object
 4   National Team Jersey Number  813 non-null    float64
 5   Player DOB                   814 non-null    object
 6   Club                         814 non-null    object
 7   Player Name                  814 non-null    object
 8    Appearances                 814 non-null    object
 9   Goals Scored                 813 non-null    object
 10  Assists Provided             813 non-null    object
 11  Dribbles per 90              813 non-null    object
 12  Interceptions per 90         813 non-null    object
 13  Tackles per 90               813 non-null    object
 14  Total Duels Won per 90       813 non-null    object
 15  Save Percentage              812 non-null    object
 16  Clean Sheets                 814 non-null    object
 17  Brand Sponsor/Brand Used     813 non-null    object
dtypes: float64(1), int64(1), object(16)
memory usage: 114.6+ KB

In [9]:
# computing and displaying summary statistics for our 2022 FIFA WORLD CUP analysis
FIFA_df.describe()

       FIFA Ranking   National Team Jersey Number
count     814.000000                   813.000000
mean       21.713759                    13.507995
std        16.159655                     7.523788
min         1.000000                     1.000000
25%         9.000000                     7.000000
50%        18.000000                    14.000000
75%        29.000000                    20.000000
max        60.000000                    26.000000

In [12]:
FIFA_df.columns

Index(['Nationality ', 'FIFA Ranking ', 'National Team Kit Sponsor',
       'Position', 'National Team Jersey Number', 'Player DOB', 'Club ',
       'Player Name ', ' Appearances', 'Goals Scored ', 'Assists Provided ',
       'Dribbles per 90', 'Interceptions per 90', 'Tackles per 90',
       'Total Duels Won per 90', 'Save Percentage', 'Clean Sheets',
       'Brand Sponsor/Brand Used'],
      dtype='object')

# Columns Discription

* Nationality : Player representing that particular nation.
* FIFA Ranking : The teams of the men's member nations of FIFA, football's 
world governing body, are ranked based on their game results with the most successful teams being ranked highest.
*  National Team Kit Sponsor : A particular brand sponsoring that football team and preparing jersey for them.
* Position : The specific role that a player takes on the field is referred to as their "position".
* National Team Jersey Number : Marking of a number behind each player's jersey.
* Player DOB : Player Date of Birth.
* Club : Club are sometimes used interchangeably by supporters, typically referring to the team within the club playing in the highest division or competition.
* Player Name : Name used in Fifa.
* Appearances : A set number of games that the player must appear on the ground for the club.
* Goals Scored : A goal is scored when the whole of the ball passes over the goal line, between the goalposts and under the crossbar, provided that no offence has been committed by the player.
* Assists Provided : Assists are awarded to a player who makes the final pass or cross before a goal is scored.
* Dribbles per 90 : Dribble per 90 means travelling with the ball in between 90 minutes.
* Interceptions per 90 : Number of times stealing the ball from your opposition in between 90 minutes.
* Tackles per 90 : To seize and throw down or stop (an opposing player with the ball) in football.
* Total Duels Won per 90 : The defensive player stopped the progression of the attacking player with the ball and didn't commit a foul, the defensive duel is considered won in those 90 minutes (and the linked offensive duel is considered lost).
* Save Percentage : It is given as by dividing the number of saves by the total number of shots on goal.
* Clean Sheets :  A goalkeeper is said to "keep a clean sheet" if they prevent their opponents scoring any goals during an entire match.
* Brand Sponsor/Brand Used : Brand sponsorship is when a brand acts as a sponsor. The brand would choose the cause to support, be it an event, a small business, or a charity.